### PR TITLE
[CLOUDSRV-4455] Fixed HTTP calls that return 4xx and 5xx errors to prope...

### PR DESCRIPTION
**Pull request by cb1kenobi**
[CLOUDSRV-4455] Fixed HTTP calls that return 4xx and 5xx errors to properly return an error.

[CLOUDSRV-4473] Updated the API to be more Node-like. Now you can create ACSApp instances yourself and not need to immeidately call a creator function.

[CLOUDSRV-4474] Changed the code so that you don't have to manually deal with session cookies. Once you login with your ACSApp instance, it is logged in for all calls until you logout. You can still manipulate the myacsApp.sessionCookieString variable, but it is not advised.

### CODE REVIEW

**Comment by jhaynie** [comment]
ACLs is missing create method:
https://github.com/cb1kenobi/acs-node-sdk/blob/81808da46ebd3d61b566c9029a275453ca72bdbe/lib/acsObjects/acls.js

which is defined by api:
http://docs.appcelerator.com/cloud/latest/#!/api/ACLs-method-create

**Comment by realpaul** [comment]
@jhaynie just fixed this problem with a PR to Chris's branch ```cb1kenobi:cloudsrv-4455``` https://github.com/cb1kenobi/acs-node-sdk/pull/1 , via JIRA ticket https://jira.appcelerator.org/browse/CLOUDSRV-4517. @cb1kenobi please kindly review it and merge it into your branch, if it looks good for you. Then we can go on using this PR for appcelerator's master acs-node-sdk branch.

**Comment by jhaynie** [comment]
@realpaul awesome, thanks.

**Comment by realpaul** [comment]
@peri18 finished load test about session management per app versus per user, via JIRA ticket CLOUDSRV-4481, and no potential memory problem found.
Code reviewed and load test passed.

**Comment by jhaynie** [comment]
@realpaul are we going to rev in package.json and push a new release? if not, when?

**Comment by realpaul** [comment]
After merging this PR, [CLOUDSRV-4455](https://jira.appcelerator.org/browse/CLOUDSRV-4455), [CLOUDSRV-4473](https://jira.appcelerator.org/browse/CLOUDSRV-4473) and [CLOUDSRV-4474](https://jira.appcelerator.org/browse/CLOUDSRV-4474) are under In QA Testing. After our qe team finishes testing, we will push this change to npm.

Our current version in npm is still 0.9.3, and we have bumped up version to 1.0.0 for our sdk new change when implementing it (JIRA story: [NODEJS-1594](https://jira.appcelerator.org/browse/NODEJS-1594)). Since both [NODEJS-1594](https://jira.appcelerator.org/browse/NODEJS-1594) and Chris's 3 tickets are all under In QA Testing, I think we can still use 1.0.0 in package.json. @jhaynie is this ok with you, or you prefer 2.0.0?

**Comment by jhaynie** [comment]
@realpaul i'm fine with 1.0 if this is stable.

**Comment by cb1kenobi** [comment]
I'd like to hold off on publishing 1.0.0 until the ACS connector is done just in case I find any other issues such as #33.

**Comment by negupta** [comment]
QE team is writing new tests for this SDK this week as well. So I would like 1) SDK to be tested by QE team and 2) ACS connector to be done before we publish this SDK to npm.

**Comment by cb1kenobi** [comment]
The ACS connector is essentially done, but may have bugs. We're in the process of testing it.

**Pull request merged**
